### ISSUE TITLE
Fatal error after authentication but before response

### ISSUE THREAD

**Issue by colinhowells** [WebDevStudios/WDS-WP-REST-API-Connect#3]
I get pretty far with this, but when the time comes for the admin screen to reflect that the post title has been changed, i get an empty

```
<div id="message" class="updated"></div>
```

as well as

'PHP Fatal error: Cannot use object of type stdClass as array'

in the logs ... so $response is failing somewhere.

Thanks for putting this together, without WP-CLI doing oAuth for the JSON API is a pain

**Comment by jtsternberg** [comment]
This just received a major update, and example file has been updated. Let me know if you run into the same issue.

**Comment by colinhowells** [comment]
Thank you sir! I'll check it out and report back.
